rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.3.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
matrix:
  exclude:
    - rvm: 1.9.2
      env: "RAILS_VERSION=3.1.0"
branches:
  only:
    - master
